### ISSUE TITLE
Depend on `bevy_asset` and `bevy_state` crates directly instead of via `bevy`

### ISSUE THREAD

**Issue by benfrankel** [NiklasEi/bevy_asset_loader#219]
If I do the following in my game's `Cargo.toml`:

```toml
bevy = { ..., default-features = false, features = [
    # A few features enabled, but no `bevy_asset` or `bevy_state`
    ...
] }
bevy_asset_loader = ...
```

Then `bevy_asset_loader` will implicitly enable the `bevy_asset` and `bevy_state` features on my own game's `bevy` dependency:

- `use bevy::prelude::*;` will pull in names from `bevy_asset` and `bevy_state`.
- `app.add_plugins(DefaultPlugins)` will set up `AssetPlugin` and `StatesPlugin`.

This is undesirable (on top of just being unexpected) if, for example, my game is using a 3rd-party alternative to `bevy_asset` that has conflicting names with `bevy_asset::prelude::*`.
